### ISSUE TITLE
Review GitHub Repo and Project permissions. (1)

### ISSUE THREAD

**Issue by ericnienhouse** [culibraries/counter-data-loader#49]
Problem: Certain GitHub actions are not enabled, write repo, create milestone.

Estimate: 1

Acceptance Criteria:

Review any GitHub repo and Project permissions that may be needed. 
Identify appropriate branch to work in (DONE: developer)
Consider: Document any needed permissions in ticket.
Make request to CU staff to enable necessary permissions.

**Comment by ericnienhouse** [comment]
Note, BB identified needs:

Write to counter-data-loader repository
Add assignee to issue
Create Milestone
Create Label

**Comment by bonnland** [comment]
Testing comment capability.

**Comment by bonnland** [comment]
Trying to test email notifications again.   After Vida changed NCAR org permissions, I can add Milestones, etc.

AFAIK I have notifications turned on for everything in my personal settings.   Note, however, that Projects are not mentioned explicitly in my notification settings.

**Comment by bonnland** [comment]
I got an email notification for the original comment.   I didn't get an additional email when I edited the comment.
