### ISSUE TITLE
Create Python Environment Description File for COUNTER Workflow (3)

### ISSUE THREAD

**Issue by ericnienhouse** [culibraries/counter-data-loader#50]
Estimate: 3

Acceptance Criteria:

Describe Python dependencies for COUNTER loader workflow.
Setup configuration for both local development and remote AWS instance.
Note: AWS environment is fairly dynamic, with frequent, unpredictable Python version/library updates.

Note: current process uses PIP as configuration tool.

**Comment by bonnland** [comment]
Initial version of conda environment file has been added and deployed within PyCharm.

Requirements are based on the packages mentioned here:

https://cu-boulder-libraries.readthedocs.io/en/latest/pages/counter.html#staging-infrastructure

**Comment by bonnland** [comment]
Reproducible Instructions for creating python environment: 

https://github.com/culibraries/counter-data-loader/blob/add-python-env/README.md
