### ISSUE TITLE
Pre processing Oxford 6 month file fails

### ISSUE THREAD

**Issue by ericnienhouse** [culibraries/counter-data-loader#69]
Problem: The Oxford "6 months" file is not pre-processed successfully and raises an error. this may be due to the file not including a column for all 12 months of a full year.

Error:

TR_B3 2021_Oxford University Press.xlsx | Usecols do not match columns, columns expected but not found: ['Metric_Type', 'Title', 'Platform', 'Access_Type']

Estimate:

Acceptance Criteria:

Determine problem.
Correct if possible (or add new stories)

Note: This appears to be due to the expected content in the incorrect sheet (ie, tab)
This may have led to the file being renamed incorrectly after pre-processing.

**Comment by bonnland** [comment]
The error likely occurred because the data sheet was not the first sheet in the Excel file.
