### ISSUE TITLE
Support TRJ1, TRB1 Type Spreadsheets in 2022 Data Load (3)

### ISSUE THREAD

**Issue by ericnienhouse** [culibraries/counter-data-loader#73]
Estimate: 3

In COUNTER 2022 data there are some TR-J1, TR-B1
These types are not currently loaded, and should be.

These may need a slight change (no access type column if found in sheet, instead found in header, assume “controlled” is access type)

Acceptance Criteria:

Support pre-processing and loading TR-J1, TR-B1 spreadsheet types.
Set access type appropriately.
Test on several spreadsheet examples.

Note: this may require refactoring to add this new report processing behavior.

**Comment by ericnienhouse** [comment]
Note deprecated code may support this.

**Comment by bonnland** [comment]
The latest commit on the "develop" branch fixes this issue.

Note that Excel files in *.XLS format are not supported; they must be saved as *.XLSX files before being processed.
