### ISSUE TITLE
Review Folio Spreadsheet Export (5)

### ISSUE THREAD

**Issue by ericnienhouse** [culibraries/counter-data-loader#74]
Estimate: 5

Tests have been done with the Folio service and a sample spreadsheet.  These sheets look similar, however, columns typically with value of '0' are empty.  These fields can assume a default of '0' for the preprocessor and loader.

Acceptance Criteria:

Review and compare Folio export spreadsheet to current COUNTER sheets.
Identify list of concerns and possible changes needed to code.

Consider: Add to error reporting when missing data found.

Timebox to 3-4 day.

**Comment by ericnienhouse** [comment]
Note: In the future we may use SUSHI or Folio APIs to access the Folio spreadsheet data.

**Comment by bonnland** [comment]
After adding some checks to address missing values, the 2021 J3 HiWire spreadsheet was loaded successfully on my local mySQL database.
